### ISSUE TITLE
增加一个教师端导出excel的功能吧

### ISSUE THREAD

**Issue by bearDream** [zbeboy/ISY#2]
# excel导出功能
> 将教室管理小组的所有成员日志导出；

**Comment by zbeboy** [comment]
@bearDream 实习日志-》小组日志中-》下载全部按钮则可以导出全部小组日志

**Comment by zbeboy** [comment]
@bearDream 你指的excel 是指什么？

**Comment by bearDream** [comment]
将小组的所有成员数据导出到excel模板中，类似附件

**Comment by zbeboy** [comment]
@bearDream 明白了，意思是要你们实习小组的组内成员个人信息，是吧？需要哪些信息？用在什么地方？
